### PR TITLE
Refactor dat parser

### PR DESCRIPTION
**Pull request by DavidVentura**
This is a mostly-mechanical translation of the current code,  without attempting to find higher level abstractions that could make the code shorter.
I've made up some names, as I don't really know what names should be assigned to these groupings

There are 4 fields which are used from the .dat files:

- Grid
- "Primitives" (Specifically, X11s)
- Port-map
- CmuxIns

I've left everything else, mostly-compatible, within `compat_dict`. There are a few very small changes, such as having indexes as integers (`CmuxIns[94]` instead of `CmuxIns["94"]`).

The new implementation also contains this _potential_ bugfix: https://github.com/YosysHQ/apicula/commit/fdc77a8996eba202f5ab76c9abe911fca080ad1a

### CODE REVIEW

**Comment by pepijndevos** [comment]
Other than CI failing it seems like an improvement

**Comment by DavidVentura** [comment]
I forgot to commit some silly changes :grin:

**Comment by pepijndevos** [comment]
Still some failures https://github.com/YosysHQ/apicula/actions/runs/7267551806/job/19855665621?pr=212#step:3:147

**Comment by pepijndevos** [comment]
Looks like things pass. I'll try to find some time to review and test on hardware and merge.

**Comment by pepijndevos** [comment]
Thank you!

**Pull request merged**
