### PR TITLE
Replace numpy arrays with lists.

### PR DESCRIPTION
**Pull request by yrabbit**
Dumb replacement of functions. The functions work only to the extent required, no more.

Creating chip databases (this includes fuzzing etc), packing and unpacking work.

Special moments:
   * you will still need numpy to create the PNG, but the import only happens when that function is called.
   * compression packing needs to be tested.
   * perhaps somewhere in places that I rarely use there are numpy calls.

Addresses https://github.com/YosysHQ/apicula/issues/224

### CODE REVIEW

**Comment by yrabbit** [comment]
It's a horror that flaps in the night, but it works, everything is concentrated in one file and can be improved if desired.

But we probably need to remove numpy from some CI config files or dependencies. I don't know about this.

**Comment by pepijndevos** [comment]
Amazing 🤩 I'll have a closer look at it later

**Comment by mmicko** [comment]
This is great. Thank you for this @yrabbit

**Review by pepijndevos — APPROVED** [review]
All that remains is to remove numpy from setup.py

https://github.com/YosysHQ/apicula/blob/8323bef886f2e96ea85fa2c632f0c454dde4c42c/setup.py#L21

We can leave it in the docker file for now, which is harmless.

As long as the basic flow works we'll see if people scream about forgotten places where numpy is used.

**Comment by mmicko** [comment]
@pepijndevos When merged I will update oss-cad-suite scripts, so we can reference people on testing on that as well

**Comment by yrabbit** [comment]
Good old runber strikes back. Let's see what kind of special wires it has...

**Comment by yrabbit** [comment]
Found it. I will need to make changes to nextpnr.

**Pull request merged**
