### PR TITLE
Improvements to readme example

### PR DESCRIPTION
**Pull request by DrJosh9000**
See #85 re the invocation of Yosys. This also uses some variables instead of requiring changing device/board in multiple places.

### CODE REVIEW

**Comment by pepijndevos** [comment]
Don't those variables need `export` to work when pasted in a shell?

**Comment by trabucayre** [comment]
Those variables are used in current shell, so there is no need to use `export`. This keyword is only required when used in subcommands

**Comment by uis246** [comment]
`export` should be passed.

1. `A=b`
2. `env | grep A=`
Result: no A

1. `export A=b`
2. `env | grep A=`
Result: A=b

**Comment by trabucayre** [comment]
yes but
````
$ TOTO="a"
$ echo $TOTO
a
```
here variable are directly used without needs of environment. But using `export` is not bad at all ;-)

**Comment by pepijndevos** [comment]
Funny I never picked up on the subprocess environment distinction. Makes sense!

**Pull request merged**
