### PR TITLE
Add dynamic clock control

### PR DESCRIPTION
**Pull request by yrabbit**
DQCE and DCS primitives are added - disabling the clock in a quadrant and dynamically selecting the clock source accordingly.

With this commit we are finally able to use clock lines 6 and 7 :)

Added examples for Tangnano1k, Tangnano4k, Tangnano9k, Primer20k, Tangnano20k boards.

From the internals: in addition to the well-known fuse tables SHORTVAL and LONGVAL, functions have been added for working with another table - LONGFUSE. It differs in that it describes the fuses of primitives with only one parameter, in contrast to two parameters for SHORTVAL and 16 parameters for LONGVAL.

### CODE REVIEW

**Comment by yrabbit** [comment]
Until the PR goes through in nextpnr, there will be errors, so we'll wait.

**Comment by yrabbit** [comment]
Well, for some time only one version of the examples will be green - until the release of yosys, since there are our changes in main.

**Comment by pepijndevos** [comment]
well we're in luck there was a release 3 days ago

**Comment by yrabbit** [comment]
Great! Now we have 2 green pieces again :)

**Pull request merged**
