### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Joshinken**
took me way too long to realize that im not pepijn. decided to make it slightly clearer to save anyone else the embarassment

### CODE REVIEW

**Comment by trabucayre** [comment]
Path you mention is always at the same location: maybe simply using `$HOME` instead `/home/YOURUSERNAME` will be better since this variable is always defined, and is the absolute path to this directory.

**Comment by uis246** [comment]
export PATH="$HOME/.local/bin:$PATH"

**Comment by pepijndevos** [comment]
Closing this and just updating the readme myself with the suggested `$HOME` variable

**Comment by Joshinken** [comment]
I forgot this was even a thing

**Pull request closed without merging**
