### PR TITLE
Add long wire constraints.

### PR DESCRIPTION
**Pull request by yrabbit**
Add ability to set constraint generation for fanout long wires.
Example:
cst.clocks["w_lw"] = "BUFS[5]=LOGIC"

Signed-off-by: YRabbit <rabbit@yrabbit.cyou>

### CODE REVIEW

**Comment by yrabbit** [comment]
As a side note, be prepared that just specifying this restriction in the fuzzer may not work if the consumer is alone.

**Comment by yrabbit** [comment]
Here's a minimal piece: 
```
    # source ff
    name = "r_src"
    dff = codegen.Primitive("DFF", name)
    dff.portmap['CLK'] = "w_clk"
    dff.portmap['D'] = "w_dummy"
    dff.portmap['Q'] = "w_lw"
    mod.wires.update({"w_dummy", "w_lw"})
    mod.primitives[name] = dff
    cst.clocks["w_lw"] = "BUFS[5]=LOGIC"
    cst.cells[name] = "R8C12[0][A]"
    # dest ff0
    name = "r_dst0"
    dff = codegen.Primitive("DFF", name)
    dff.portmap['CLK'] = "w_clk"
    dff.portmap['D'] = "w_lw"
    dff.portmap['Q'] = "w_dst2_d"
    mod.wires.update({"w_dst2_d"})
    mod.primitives[name] = dff
    cst.cells[name] = "R2C2[0][B]"
    # dest ff2
    name = "r_dst2"
    dff = codegen.Primitive("DFFS", name)
    dff.portmap['CLK'] = "w_clk"
    dff.portmap['D'] = "w_lw"
    dff.portmap['Q'] = "w_led"
    dff.portmap['SET'] = "w_dst2_d"
    mod.primitives[name] = dff
    cst.cells[name] = "R3C3[0][B]"

```

**Comment by yrabbit** [comment]
And UNK32-39 are long wires :)

**Comment by pepijndevos** [comment]
Would be good to update
https://github.com/YosysHQ/apicula/blob/ca1529e508c5cb052462a5cd9dce101c11e91efd/apycula/wirenames.py#L30

**Comment by yrabbit** [comment]
I feared there would be effects from moving to another category:)

https://github.com/YosysHQ/nextpnr/blob/e926cddca274423ea414e61a07deb785ee63c92d/gowin/arch.cc#L469-L473

**Comment by pepijndevos** [comment]
Hm, yes there would. A low-risk alternative is writing it down in the `/doc` folder.
Actually, I should probably do that to write down the MUX and ALU stuff I've found so far.

**Comment by yrabbit** [comment]
The constraint syntax;
CLOCK_LOC   "net_name"   clocks=fanout
where
  clocks:
    BUFG[0-7]    eight master clocks
    BUFS[0-7]     eight long wires
    LOCAL_CLOCK   ``not route to the clock line'' whatever this means

  fanout:
    CLK
    CE
    SR   set/reset/clear/preset
    LOGIC none above 

| may be used as OR. like
CLOCK_LOC "some-net"  BUFS[3]=CLK|CE

**Comment by yrabbit** [comment]
Ah yes, the last thing left to add is that there are complete analogs of clock mechanisms:
LB00, LBO1, 
LB0-7
LT0,1,2,4
LT13
LT00,10,20,30 and there are two things to do:
* find the connection from the spine to the T and from the DFF outputs to the spine
* teach nextpnr to use these long lines correctly.

**Comment by yrabbit** [comment]
> Hm, yes there would. A low-risk alternative is writing it down in the `/doc` folder.
Yes, I think I'll document it in a doc :)

**Pull request merged**
